import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { Icon } from './icons';
import { agent, isSummary, type ClientRow, type Home, type TransactionList } from './agentApi';
import type { Session } from './api';
import type { ScreenId } from './App';
import { fmtDate, t } from './i18n';
import countries from './assets/worldCountries.json';

export function AgentBrand(){return <span className="a-brand a-brand-independent"><span className="a-word"><span className="wordmark">ScoutBox</span><sup>TM</sup></span><span className="a-agent-signature"><svg viewBox="0 0 34 30" aria-hidden="true"><path d="M3 26 16 3l13 23M9 20h15M20 8l10-5"/><circle cx="30" cy="3" r="2.5"/></svg><span>agent</span></span></span>}
export function AgentMap({counts={},selected,onSelect,decorative=false}:{counts?:Record<string,number>;selected?:string|null;onSelect?:(id:string)=>void;decorative?:boolean}){
 return <svg className="a-world-map" viewBox="0 0 720 380" preserveAspectRatio="xMidYMid meet" role={decorative?undefined:"group"} aria-hidden={decorative||undefined} aria-label={decorative?undefined:"Countries in your visible client records"}><defs><linearGradient id={decorative?'a-map-entry':'a-map-fill'} x2="1" y2="1"><stop stopColor="#b297ff"/><stop offset="1" stopColor="#6e4cce"/></linearGradient></defs>{countries.map(c=><path key={c.name} d={c.path} className={counts[c.id]?'populated':''} style={{fill:counts[c.id]?`url(#${decorative?'a-map-entry':'a-map-fill'})`:undefined,opacity:selected && selected!==c.id && counts[c.id] ? 0.4 : 1}} onClick={counts[c.id]&&onSelect?()=>onSelect(c.id):undefined} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&counts[c.id]&&onSelect){e.preventDefault();onSelect(c.id)}}} tabIndex={counts[c.id]&&onSelect?0:undefined} role={counts[c.id]&&onSelect?'button':undefined} aria-label={counts[c.id]?`${c.name}: ${counts[c.id]} client ${counts[c.id]===1?"record":"records"}`:undefined}>{!decorative&&counts[c.id]?<title>{c.name} · {counts[c.id]} client records</title>:null}</path>)}</svg>
}
const pretty=(s:string)=>s.replace(/_/g,' ').toLowerCase().replace(/^./,c=>c.toUpperCase());
export const AGENT_PAGE_INFO:Record<ScreenId,{title:string;description:string;icon:string}>={
 home:{title:'Agency overview',description:'Your clients, your markets, your next move.',icon:'home'},
 clients:{title:'Client portfolio',description:'Representation, relationships and the work behind every career.',icon:'users'},
 transactions:{title:'Transaction desk',description:'Manage parties, documents and the next required action.',icon:'briefcase'},
 opportunities:{title:'Opportunities',description:'The market, through your clients’ permitted opportunities.',icon:'globe'},
 profile:{title:'Professional profile',description:'Your identity, credentials and regulatory standing.',icon:'badge-check'},
 compliance:{title:'Compliance centre',description:'Review contexts, disclosures and outstanding consents.',icon:'shield-check'},
 agency:{title:'Agency management',description:'Your people, permissions and operating records.',icon:'building'},
 inbox:{title:'Correspondence',description:'Requests, responses and developments across your portfolio.',icon:'inbox'}
};
export function AgentHeading({screen}:{screen:ScreenId}){const p=AGENT_PAGE_INFO[screen];return <header className="a-page-heading"><div><span>SCOUTBOX AGENT / {screen==='home'?'BUSINESS OVERVIEW':'WORKSPACE'}</span><h2>{p.title}</h2><p>{p.description}</p></div><div className="a-page-symbol"><Icon name={p.icon} size={29}/></div></header>}

export function AgentDashboard({session,tick,home,onNavigate}:{session:Session;tick:number;home:Home;onNavigate:(id:ScreenId)=>void}){
 const [clients,setClients]=useState<ClientRow[]|null>(null),[transactions,setTransactions]=useState<TransactionList|null>(null),[error,setError]=useState(''),[country,setCountry]=useState<string|null>(null),[period,setPeriod]=useState(6),[query,setQuery]=useState('');
 useEffect(()=>{let live=true;setClients(null);setTransactions(null);setError('');Promise.allSettled([agent.clients(session),agent.transactions(session)]).then(([c,tx])=>{if(!live)return;if(c.status==='fulfilled')setClients(c.value.items);else setError('Client geography is unavailable for this account.');if(tx.status==='fulfilled')setTransactions(tx.value);});return()=>{live=false}},[session,tick]);
 const own=(clients??[]).filter(r=>!isSummary(r));
 const countryCounts=useMemo(()=>{const result:Record<string,number>={};for(const r of clients??[]){if(!isSummary(r)&&r.status==='active'&&r.client?.country)result[r.client.country]=(result[r.client.country]??0)+1}return result},[clients]);
 const markets=Object.entries(countryCounts).sort((a,b)=>b[1]-a[1]);
 const countryName=(id:string)=>countries.find(c=>c.id===id)?.name??id;
 const shown=own.filter(r=>(!country||r.client?.country===country)&&(r.client?.name??'').toLowerCase().includes(query.toLowerCase()));
 const now=new Date();const months=Array.from({length:period},(_,i)=>new Date(now.getFullYear(),now.getMonth()-period+1+i,1));
 const series=months.map(m=>own.filter(r=>r.proposedAt&&new Date(r.proposedAt).getMonth()===m.getMonth()&&new Date(r.proposedAt).getFullYear()===m.getFullYear()).length);const max=Math.max(1,...series);const points=series.map((n,i)=>`${20+i*440/(period-1)},${125-n/max*95}`).join(' ');
 const distribution=[['Active',home.counts.active,'#aa88ff'],['Pending',home.counts.pending,'#e7b8d8'],['Disputed',home.counts.disputed,'#ef8d92'],['Expired',home.counts.expired,'#5b5573']] as const;const total=distribution.reduce((a,x)=>a+x[1],0);let sum=0;const ring=distribution.map(x=>{const start=sum;sum+=x[1]/Math.max(1,total)*100;return `${x[2]} ${start}% ${sum}%`}).join(',');
 return <div className="a-dashboard">
 <div className="a-kpis">{[{label:'Active clients',value:home.counts.active,icon:'users',test:'home-active',sub:'Confirmed representation',target:'clients'},{label:'Pending requests',value:home.counts.pending,icon:'send',test:'home-pending',sub:'Awaiting a client decision',target:'inbox'},{label:'Live transactions',value:transactions?.counts.live??'—',icon:'briefcase',sub:'In your permitted workspace',target:'transactions'},{label:'Expiring agreements',value:home.counts.expiringSoon,icon:'calendar-days',sub:'Approaching their end date',target:'clients'}].map((k,i)=><button key={k.label} className={`a-kpi tone-${i}`} onClick={()=>onNavigate(k.target as ScreenId)} data-testid={k.test}><span><Icon name={k.icon} size={18}/>{k.label}<Icon name="arrow-up-right" size={14}/></span><strong>{k.value}</strong><small>{k.sub}</small></button>)}</div>
 <div className="a-dashboard-grid"><section className="a-card a-market"><header><div><span className="a-overline">PORTFOLIO INTELLIGENCE</span><h3>Global client footprint</h3></div><button className="a-quiet" onClick={()=>setCountry(null)}>All markets <Icon name="globe" size={14}/></button></header><AgentMap counts={countryCounts} selected={country} onSelect={id=>setCountry(country===id?null:id)}/><div className="a-map-caption"><span><i/> Recorded client countries</span><span>{markets.length} markets · active relationships</span></div><div className="a-market-bars">{markets.length?markets.slice(0,4).map(([id,n])=><button key={id} aria-pressed={country===id} onClick={()=>setCountry(country===id?null:id)}><span>{countryName(id)}</span><i><b style={{width:`${n/Math.max(...markets.map(x=>x[1]))*100}%`}}/></i><strong>{n}</strong></button>):<p className="dim">{error||(!clients?'Loading your portfolio…':'No country data is available for active client records.')}</p>}</div></section>
 <section className="a-card a-portfolio"><header><div><span className="a-overline">REPRESENTATION</span><h3>Portfolio balance</h3></div><Icon name="pie-chart" size={20}/></header><div className="a-ring" style={{'--ring':total?`conic-gradient(${ring})`:'#393149'} as CSSProperties}><div><strong>{total}</strong><span>in these states</span></div></div><ul>{distribution.map(([name,n,color])=><li key={name}><i style={{background:color}}/><span>{name}</span><b>{n}</b></li>)}</ul><footer>Current records visible to your account.</footer></section>
 <section className="a-card a-activity"><header><div><span className="a-overline">BUSINESS ACTIVITY</span><h3>Representation requests</h3></div><select aria-label="Activity period" value={period} onChange={e=>setPeriod(Number(e.target.value))}><option value={6}>Last 6 months</option><option value={12}>Last 12 months</option></select></header><div className="a-chart-total"><strong>{clients?series.reduce((a,b)=>a+b,0):"—"}</strong><span>records opened in this period</span></div>{clients?<svg className="a-area-chart" viewBox="0 0 480 155" role="img" aria-label={`Monthly representation requests: ${series.join(', ')}`}><defs><linearGradient id="a-area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#a27bff" stopOpacity=".6"/><stop offset="1" stopColor="#a27bff" stopOpacity="0"/></linearGradient></defs>{[30,62,94,126].map(y=><path key={y} d={`M20 ${y}H460`} stroke="#ffffff10" strokeDasharray="3 5"/>)}<polygon points={`20,130 ${points} 460,130`} fill="url(#a-area)"/><polyline points={points} fill="none" stroke="#c0a3ff" strokeWidth="2.2"/>{series.map((n,i)=><circle key={i} cx={20+i*440/(period-1)} cy={125-n/max*95} r="3" fill="#f0cbdd"><title>{months[i].toLocaleDateString('en-GB',{month:'short',year:'numeric'})}: {n}</title></circle>)}</svg>:<p className="a-empty">{error||"Loading activity…"}</p>}<div className="a-chart-months">{months.map(m=><span key={m.toISOString()}>{m.toLocaleDateString('en-GB',{month:'short'})}</span>)}</div></section>
 <section className="a-card a-desk-status"><header><div><span className="a-overline">TRANSACTION DESK</span><h3>Next steps</h3></div><Icon name="briefcase" size={20}/></header>{[{label:'Awaiting confirmation',n:transactions?.counts.awaitingConfirmation},{label:'Compliance pending',n:transactions?.counts.pending},{label:'Blocked',n:transactions?.counts.blocked},{label:'Ready to proceed',n:transactions?.counts.ready}].map(x=><button key={x.label} onClick={()=>onNavigate('transactions')}><span>{x.label}</span><strong>{x.n??'—'}</strong><Icon name="arrow-up-right" size={14}/></button>)}<footer>Readiness is a workflow state, not an agreement or signing.</footer></section></div>
 <section className="a-card a-client-register"><header><div><span className="a-overline">YOUR BUSINESS</span><h3>{country?countryName(country):'Client portfolio'}</h3></div><label><Icon name="search" size={15}/><input aria-label="Find a portfolio client" placeholder="Search clients" value={query} onChange={e=>setQuery(e.target.value)}/></label><button onClick={()=>onNavigate('clients')}>View portfolio <Icon name="arrow-up-right" size={14}/></button></header><div className="a-table-scroll"><table><thead><tr><th>Client</th><th>Representation</th><th>Jurisdiction</th><th>End date</th><th>Status</th></tr></thead><tbody>{shown.slice(0,8).map(r=><tr key={r.id}><td><span className="a-mini-avatar">{(r.client?.name??'').split(' ').map(n=>n[0]).slice(0,2).join('')}</span>{r.client?.name??'Restricted record'}</td><td>{r.scope.map(s=>t(`scope.${s}` as Parameters<typeof t>[0])).join(', ')}</td><td>{r.jurisdiction??'—'}</td><td>{r.endAt?fmtDate(r.endAt):'—'}</td><td><span className={`pill ${r.status==='active'?'green':r.status==='disputed'?'red':'blue'}`}>{pretty(r.status)}</span></td></tr>)}</tbody></table></div>{!shown.length&&<p className="a-empty">{error||(clients?'No visible client records match this view.':'Loading client records…')}</p>}</section>
 </div>
}
