import assert from 'node:assert/strict';
import { clipTime, validClipRange } from '../scoutbox-club/src/proClipModel.ts';
import { csvContent } from '../scoutbox-club/src/proExport.ts';
assert.equal(validClipRange(0, 2.3, 2.3), true);
assert.equal(validClipRange(null, 2, 3), false);
assert.equal(validClipRange(2, 1, 3), false);
assert.equal(validClipRange(-1, 1, 3), false);
assert.equal(validClipRange(0, 4, 3), false);
assert.equal(validClipRange(1, 1.0001, 3), false);
assert.equal(validClipRange(0, 601, 700), false);
assert.equal(validClipRange(5, 605, 700), true);
assert.equal(validClipRange(0, Infinity, Infinity), false);
assert.equal(clipTime(59.996), '01:00.00');
assert.equal(clipTime(0), '00:00.00');
assert.equal(clipTime(NaN), '00:00.00');
assert.equal(clipTime(.04), '00:00.04');
const rows = [['=SUM(A1)', 'a,b', 'two"quotes', 'line\nbreak'], ['+1', '@x', '-2', null]];
const original = structuredClone(rows);
const csv = csvContent(['A','B','C','D'], rows);
assert.ok(csv.startsWith('\uFEFF"A","B","C","D"\r\n'));
assert.ok(csv.includes("\"'=SUM(A1)\""));
assert.ok(csv.includes('"a,b","two""quotes","line\nbreak"'));
assert.ok(csv.includes("\"'+1\",\"'@x\",\"'-2\",\"\""));
assert.deepEqual(rows, original);
console.log('Pro tools: 18 checks passed (clip boundaries, rounding, timecodes and CSV escaping).');
